### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by cheny36** [allenjiang17/theSearchForEden#18]
I think mixins or something akin to it would be very useful, as we will begin to develop properties, and we want these properties to be applicable and reuseable in a broad sense. The easiest way to do this is that if each "object" in our project can inherit multiple properties, which is similar to the mixin concept.

**Comment by cheny36** [comment]
NVM, I'll see if I can get around it for now

**Comment by allenjiang17** [comment]
oh what happened
