### ISSUE TITLE
Clear Game Data Bug

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#22]
For some reason, when hit "Clear Game Data," I start my new game with 3 coins and 5 Chewed-up Garments.

https://github.com/user-attachments/assets/f6e12856-9c6a-4dbb-9dc0-2454dfe993f4

**Comment by allenjiang17** [comment]
that is becuase i set it so. haha. was testing the tailor function and didnt want to spent 15 min beating up moth and rust for the garments
