### ISSUE TITLE
Convo: Inventory Format

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#27]
Just wanted to start a conversation here. There seems to be two main ways of drawing from an inventory in games. 

1. All possessed items can be accessed all the time. This is the current format, and also the format for Kingdom of Loathing.
2. Only a limited number of items can be immediately accessible. This is more of a real-life format, as a real-life bag has limited storage. All other collected items need to be stored somewhere in the game. In Stardew Valley this is a chest you have to build. In Pokemon this is a computer in the Pokemon Center. In Runescape this is a bank.

I am leaning toward Option #2, because it makes the game more challenging, and right now I feel that the game is too easy. What do you all think?

**Comment by allenjiang17** [comment]
Hmmmm....im not sure. I agree Option 2 might be more difficult, but this feel low ticket for me for now. I'd rather increase difficulty by making the combat system harder/adding other elements than this. Usually for me having to go through chests to find stuff is more annoying than actually difficult....I was super happy when in pokemon violet they got rid of all that and you just hae everything on you all the time

**Comment by Larinitus** [comment]
Gotcha, I don't feel strongly about this, so we can leave things as is then.
