### ISSUE TITLE
save gameState to localStorage so you don't start over everytime

### ISSUE THREAD

**Issue by allenjiang17** [allenjiang17/theSearchForEden#4]

**Comment by cheny36** [comment]
Done. see the `useStateLocal` and `effectHook` functions in `src/game.jsx`.

TODO:
figure out loading and saving `location`, which breaks because there are other effect hooks on location that doesn't play well with changing the location on load.

**Comment by allenjiang17** [comment]
i will take a look at location and the issue with its useEffect hook

**Comment by allenjiang17** [comment]
fixed. i couldnt find a solution to get rid of the useEffect hook in location, but i changed the currentEvent state to be owned by location rather than game. I think this cleans it up a bit -- the currentEvent is generated randomly and owned by location, and we should only save location.
