### ISSUE TITLE
Feature Request: Distinction between Locations

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#7]
Sometimes, not all locations are in the same category, and it might make more sense to distinguish a few from the rest.

For example, in "house", there are four options: Bedroom, Prayer closet, Living room, City of Destruction. City of Destruction is technically outside the house, so it would make sense if it was displayed differently.

Another example is the Wilderness. The Lost Man, Field of Manna, Valley of Stones, Desert of Wandering, Bronze Serpent, and Yam Suph are all places in the Wilderness. But I envision the other options to be places outside (but adjacent) to the Wilderness.

One option I can think of is to have a large box (similar to the event box) that is labeled with the location title--"Your House" or something like that. And all options within that location goes inside that box. All options outside of that location goes outside of that box.

I also recognize that once we introduce images, there could be a redesign, so this whole thing may be moot.

**Comment by allenjiang17** [comment]
in a nested location structure, it should be:

Top level (world) -> house, and top level (world) -> city of destruction. so if you want to go from house to city destruction, it should be "go back to world/ go outside", and then from the top level select city of destruction.

likewise any locations adjacent to wilderness would require moving up a level from wilderness to its parent location, and selecting that location.

This would the precursor to the image based navigation -- this is how KoL does it

**Comment by Larinitus** [comment]
Okay, thanks for clarification, makes sense. I just made some changes and merged my branch.
