### ISSUE TITLE
New Line in Strings?

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#8]
How can we have line spacing between text in strings in Javascript? I tried "\n" but it doesn't work. For example, in theLostMan.

**Comment by allenjiang17** [comment]
just need to add the whitespace prewrap class to those description boxes.

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by allenjiang17** [comment]
fixed

**Comment by allenjiang17** [comment]
fixed -- whitespace prewrap in top container
