### ISSUE TITLE
Feature Request: Spiritual HP Usage

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#9]
Currently, all combat affects Physical HP. But I'm thinking that this should only be true of physical enemies. 

I'm thinking that spiritual enemies only have Spiritual HP, and they also only do damage to Spiritual HP. After all, fighting Sloth or Gluttony is a purely mental/psychological battle.

But if either Physical HP or Spiritual HP reaches 0, then we are unable to perform any actions (except to restore our health).

**Comment by allenjiang17** [comment]
yep -- this is a bug, should be easily changeable

**Comment by allenjiang17** [comment]
fixed -- spiritual enemies now damage spiritual hp
